defaults: &defaults
  host: 127.0.0.1
  port: 27017
  database: <%= "content-#{Rails.env}" %>

development:
  <<: *defaults

test:
  <<: *defaults

cucumber:
  <<: *defaults

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOHQ_URL'] %>
  database: content-production
