defaults: &defaults
  host: 127.0.0.1
  port: 27017

development:
  <<: *defaults
  database: content-development

test:
  <<: *defaults
  database: content-test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGO_URL'] %>
  database: content-production
  username: <%= ENV['MONGO_USERNAME'] %>
  password: <%= ENV['MONGO_PASSWORD'] %>
